//! The writer: CoreLogos → Rust token structure.
//!
//! One domain trait, [`ProjectRust`], implemented once per CoreLogos node kind —
//! the verb-belongs-to-noun discipline. Each node projects the Rust tokens it
//! already *is* and composes its children; totality is mechanical, because the
//! closed [`CoreItem`] enum is matched with no wildcard arm and every child slot
//! is itself a `ProjectRust` node. The [`NameResolver`] is threaded down the call
//! tree and touched only at the identifier-bearing leaves ([`Identifier`] and each
//! path segment), so a stringless Core realizes names at the last moment and
//! nowhere else.
//!
//! ## The five-synthesis rule, enforced by construction
//!
//! Projection adds no meaning. The only things it is allowed to synthesize are the
//! five ruled translations, and every one has exactly one home:
//!
//! 1. **Dotted → `::`** — [`PathNode::project`], the sole place `::` is emitted.
//! 2. **Delimiter re-sugaring** — the `(…)` of a newtype body, the `{…}` of a
//!    struct/enum body, the `<…>` of a generic application/parameter list, and the
//!    `(…)` of a derive list, each chosen by the owning node's kind.
//! 3. **Stored-identifier realization** — [`Identifier::project`] resolves an index
//!    that is already the meaning; it never invents a name.
//! 4. **Formatting** — owned entirely by the single `prettyplease` pass in
//!    [`RustSource::project_item`]; no node emits final whitespace.
//! 5. **The `// @generated` header** — a fixed module literal, emitted only by
//!    [`RustSource::project_module`].
//!
//! Nothing semantic is synthesized: visibility, the derive sets, struct-vs-newtype,
//! attribute order, cfg predicates, field names, and wrapped types are all present
//! in the CoreLogos value and transcribed.

use core_logos::{
    Alias, Attribute, ConfigurationAttribute, ConfigurationPredicate, CoreItem, DeriveGroup,
    Enumeration, Field, GenericParameter, Generics, HelperDerive, LifetimeParameter, Newtype,
    PathNode, Struct, TypeApplication, TypeParameter, TypeReference, Variant, VariantPayload,
    Visibility,
};
use name_table::{Identifier, NameResolver};
use proc_macro2::TokenStream;
use quote::quote;

use crate::error::Error;

/// The fixed module header prepended once per generated module, matching the
/// schema-rust oracle. One of the five allowed syntheses.
pub const GENERATED_HEADER: &str = "// @generated by schema-rust";

/// The single projection verb, implemented once per CoreLogos node kind. Returns a
/// `proc_macro2::TokenStream` — token *structure and content*, never final bytes —
/// so formatting authority stays with the one `prettyplease` pass. Resolving a name
/// can fail on a torn Core/NameTable pair, so the verb is fallible.
pub trait ProjectRust {
    /// Realize this node as Rust tokens, resolving any identifiers it bears through
    /// the read-only resolver at the last moment.
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

/// The inner-meta form of an attribute — its content without the `#[ ]` wrapper —
/// used both for the outer attribute line and, recursively, inside a `cfg_attr`.
/// A second verb on the one noun that needs it, rather than a projection-time flag.
trait ProjectAttributeMeta {
    /// The attribute's meta tokens, e.g. `derive(Clone, Debug)` or `rustfmt::skip`.
    fn project_meta<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

/// The concatenated `#[…]` attribute preamble in stored order — the verb on the
/// attribute-vector noun, so no free composition helper is needed. Each attribute
/// still owns its own projection.
trait ProjectAttributePreamble {
    /// Project every attribute to its `#[…]` line and concatenate in stored order.
    fn project_preamble<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

impl ProjectAttributePreamble for [Attribute] {
    fn project_preamble<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let lines = self
            .iter()
            .map(|attribute| attribute.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #(#lines)* })
    }
}

impl ProjectRust for Identifier {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = names.resolve(*self)?;
        // Parse rather than `Ident::new` so path keywords (`super`, `crate`) and
        // any lexically valid segment realize as their own tokens without panic.
        name.as_str()
            .parse::<TokenStream>()
            .map_err(|error| Error::Project(error.to_string()))
    }
}

impl ProjectRust for PathNode {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let segments = self
            .segments
            .iter()
            .map(|segment| segment.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The sole home of the dotted → `::` translation.
        Ok(quote! { #(#segments)::* })
    }
}

impl ProjectRust for TypeReference {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            TypeReference::Path(path) => path.project(names),
            TypeReference::Application(application) => application.project(names),
        }
    }
}

impl ProjectRust for TypeApplication {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let head = self.head.project(names)?;
        let arguments = self
            .arguments
            .iter()
            .map(|argument| argument.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `<…>` re-sugaring — one of the five allowed syntheses.
        Ok(quote! { #head<#(#arguments),*> })
    }
}

impl ProjectRust for Visibility {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        Ok(match self {
            Visibility::Public => quote! { pub },
            Visibility::Crate => quote! { pub(crate) },
            Visibility::Module(path) => {
                let path = path.project(names)?;
                quote! { pub(in #path) }
            }
            // The empty token stream: the "no `pub`" special case dissolves here.
            Visibility::Private => TokenStream::new(),
        })
    }
}

impl ProjectAttributeMeta for Attribute {
    fn project_meta<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            Attribute::Derive(group) => group.project(names),
            Attribute::ToolPath(path) => path.project(names),
            Attribute::HelperDerive(helper) => helper.project(names),
            Attribute::Configuration(configuration) => configuration.project(names),
        }
    }
}

impl ProjectRust for Attribute {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let meta = self.project_meta(names)?;
        Ok(quote! { #[#meta] })
    }
}

impl ProjectRust for DeriveGroup {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let paths = self
            .paths
            .iter()
            .map(|path| path.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // A trailing comma: prettyplease preserves it in the wrapped (multi-line)
        // derive the width-heavy goldens produce, and strips it when the derive
        // stays on one line — so one emission is byte-exact in both layouts.
        Ok(quote! { derive(#(#paths,)*) })
    }
}

impl ProjectRust for HelperDerive {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let path = self.path.project(names)?;
        let derived = self.derived.project(names)?;
        Ok(quote! { #path(#derived) })
    }
}

impl ProjectRust for ConfigurationAttribute {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let predicate = self.predicate.project(names)?;
        let inner = self.inner.project_meta(names)?;
        Ok(quote! { cfg_attr(#predicate, #inner) })
    }
}

impl ProjectRust for ConfigurationPredicate {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            ConfigurationPredicate::Feature(identifier) => {
                let name = names.resolve(*identifier)?;
                let literal = syn::LitStr::new(name.as_str(), proc_macro2::Span::call_site());
                Ok(quote! { feature = #literal })
            }
        }
    }
}

impl ProjectRust for Generics {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        if self.parameters.is_empty() {
            return Ok(TokenStream::new());
        }
        let parameters = self
            .parameters
            .iter()
            .map(|parameter| parameter.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { <#(#parameters),*> })
    }
}

impl ProjectRust for GenericParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            GenericParameter::Type(parameter) => parameter.project(names),
            GenericParameter::Lifetime(parameter) => parameter.project(names),
        }
    }
}

impl ProjectRust for TypeParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        if self.bounds.is_empty() {
            return Ok(name);
        }
        let bounds = self
            .bounds
            .iter()
            .map(|bound| bound.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #name: #(#bounds)+* })
    }
}

impl ProjectRust for LifetimeParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = names.resolve(self.name)?;
        format!("'{}", name.as_str())
            .parse::<TokenStream>()
            .map_err(|error| Error::Project(error.to_string()))
    }
}

impl ProjectRust for Field {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let type_reference = self.type_reference.project(names)?;
        Ok(quote! { #visibility #name: #type_reference })
    }
}

impl ProjectRust for Variant {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        match &self.payload {
            VariantPayload::Unit => Ok(name),
            VariantPayload::Tuple(types) => {
                let types = types
                    .iter()
                    .map(|type_reference| type_reference.project(names))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(quote! { #name(#(#types),*) })
            }
            VariantPayload::Struct(fields) => {
                let fields = fields
                    .iter()
                    .map(|field| field.project(names))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(quote! { #name { #(#fields),* } })
            }
        }
    }
}

impl ProjectRust for Newtype {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let wrapped = self.wrapped.project(names)?;
        Ok(quote! { #attributes #visibility struct #name(#wrapped); })
    }
}

impl ProjectRust for Struct {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let fields = self
            .fields
            .iter()
            .map(|field| field.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #attributes #visibility struct #name #generics { #(#fields),* } })
    }
}

impl ProjectRust for Enumeration {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let variants = self
            .variants
            .iter()
            .map(|variant| variant.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #attributes #visibility enum #name #generics { #(#variants),* } })
    }
}

impl ProjectRust for Alias {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let target = self.target.project(names)?;
        Ok(quote! { #attributes #visibility type #name #generics = #target; })
    }
}

impl ProjectRust for CoreItem {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        // Exhaustive over the closed algebra — no wildcard arm, so a new item kind
        // is a compile error until its projection is written.
        match self {
            CoreItem::Newtype(newtype) => newtype.project(names),
            CoreItem::Struct(structure) => structure.project(names),
            CoreItem::Enumeration(enumeration) => enumeration.project(names),
            CoreItem::Alias(alias) => alias.project(names),
        }
    }
}

/// A rendered Rust textual form — the output noun of the writer and the input noun
/// of the reader. It carries the projected Rust source text; formatting is
/// prettyplease's, owned by the constructors here.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustSource(String);

impl RustSource {
    /// Wrap already-rendered Rust text (e.g. a golden file read from disk).
    pub fn new(text: impl Into<String>) -> Self {
        Self(text.into())
    }

    /// The rendered text.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consume into the owned text.
    pub fn into_string(self) -> String {
        self.0
    }

    /// Project one CoreLogos item to byte-exact Rust: assemble its token structure
    /// through [`ProjectRust`], then run the single `prettyplease` pass that owns
    /// all formatting. The attribute preamble (including `#[rustfmt::skip]`) is
    /// stored data on the item, so it is part of the projected tokens, not
    /// prepended here.
    pub fn project_item<Resolver: NameResolver + ?Sized>(
        item: &CoreItem,
        names: &Resolver,
    ) -> Result<Self, Error> {
        let tokens = item.project(names)?;
        let file: syn::File =
            syn::parse2(tokens).map_err(|error| Error::Project(error.to_string()))?;
        Ok(Self(prettyplease::unparse(&file)))
    }

    /// Project a whole module: the fixed `// @generated` header, then each item's
    /// single-pass render, separated by a blank line — the schema-rust module
    /// shape. Per-item byte-exactness is the acceptance unit; this is the
    /// convenience whole-module view.
    pub fn project_module<Resolver: NameResolver + ?Sized>(
        items: &[CoreItem],
        names: &Resolver,
    ) -> Result<Self, Error> {
        let mut text = String::new();
        text.push_str(GENERATED_HEADER);
        text.push_str("\n\n");
        for item in items {
            text.push_str(Self::project_item(item, names)?.as_str());
            text.push('\n');
        }
        Ok(Self(text))
    }
}
