//! The writer: CoreLogos → Rust token structure.
//!
//! One domain trait, [`ProjectRust`], implemented once per CoreLogos node kind —
//! the verb-belongs-to-noun discipline. Each node projects the Rust tokens it
//! already *is* and composes its children; totality is mechanical, because the
//! closed [`CoreItem`] enum is matched with no wildcard arm and every child slot
//! is itself a `ProjectRust` node. The [`NameResolver`] is threaded down the call
//! tree and touched only at the identifier-bearing leaves ([`Identifier`] and each
//! path segment), so a stringless Core realizes names at the last moment and
//! nowhere else.
//!
//! ## The five-synthesis rule, enforced by construction
//!
//! Projection adds no meaning. The only things it is allowed to synthesize are the
//! five ruled translations, and every one has exactly one home:
//!
//! 1. **Dotted → `::`** — [`PathNode::project`], the sole place `::` is emitted.
//! 2. **Delimiter re-sugaring** — the `(…)` of a newtype body, the `{…}` of a
//!    struct/enum body, the `<…>` of a generic application/parameter list, and the
//!    `(…)` of a derive list, each chosen by the owning node's kind.
//! 3. **Stored-identifier realization** — [`Identifier::project`] resolves an index
//!    that is already the meaning; it never invents a name.
//! 4. **Formatting** — owned entirely by the single `prettyplease` pass in
//!    [`RustSource::project_item`]; no node emits final whitespace.
//! 5. **The `// @generated` header** — a fixed module literal, emitted only by
//!    [`RustSource::project_module`].
//!
//! Nothing semantic is synthesized: visibility, the derive sets, struct-vs-newtype,
//! attribute order, cfg predicates, field names, and wrapped types are all present
//! in the CoreLogos value and transcribed.

use core_logos::{
    Alias, ArrayExpression, AssociatedType, Attribute, Block, Call, Callee, ClosureExpression,
    ConfigurationAttribute, ConfigurationPredicate, Const, CoreItem, DeriveGroup, Enumeration,
    Expression, Field, Function, GenericParameter, Generics, HelperDerive, ImplBlock, ImplItem,
    ImplTraitType, IndexExpression, IntegerLiteral, IntegerRepresentation, LetBinding,
    LetStatement, LifetimeParameter, Match, MatchArm, MethodCall, Module, Newtype, Parameter,
    PathNode, Pattern, PatternElement, QualifiedPath, RangeExpression, Receiver,
    ReferenceExpression, ReferenceMutability, ReferenceType, SliceType, Statement, Struct,
    TryExpression, TupleExpression, TupleFieldAccess, TupleType, TupleVariantPattern,
    TypeApplication, TypeParameter, TypeReference, Use, Variant, VariantPayload, Visibility,
};
use name_table::{Identifier, NameResolver};
use proc_macro2::TokenStream;
use quote::quote;

use crate::error::Error;

/// The module header prepended once per generated module: `logos` names the
/// generator and the version is this emitting crate's own `CARGO_PKG_VERSION`,
/// stamped mechanically by the build so the provenance can never silently drift
/// from a hand-maintained string. One of the five allowed syntheses.
pub const GENERATED_HEADER: &str = concat!("// @generated by logos ", env!("CARGO_PKG_VERSION"));

/// The single projection verb, implemented once per CoreLogos node kind. Returns a
/// `proc_macro2::TokenStream` — token *structure and content*, never final bytes —
/// so formatting authority stays with the one `prettyplease` pass. Resolving a name
/// can fail on a torn Core/NameTable pair, so the verb is fallible.
pub trait ProjectRust {
    /// Realize this node as Rust tokens, resolving any identifiers it bears through
    /// the read-only resolver at the last moment.
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

/// The inner-meta form of an attribute — its content without the `#[ ]` wrapper —
/// used both for the outer attribute line and, recursively, inside a `cfg_attr`.
/// A second verb on the one noun that needs it, rather than a projection-time flag.
trait ProjectAttributeMeta {
    /// The attribute's meta tokens, e.g. `derive(Clone, Debug)` or `rustfmt::skip`.
    fn project_meta<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

/// The concatenated `#[…]` attribute preamble in stored order — the verb on the
/// attribute-vector noun, so no free composition helper is needed. Each attribute
/// still owns its own projection.
trait ProjectAttributePreamble {
    /// Project every attribute to its `#[…]` line and concatenate in stored order.
    fn project_preamble<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

impl ProjectAttributePreamble for [Attribute] {
    fn project_preamble<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let lines = self
            .iter()
            .map(|attribute| attribute.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #(#lines)* })
    }
}

impl ProjectRust for Identifier {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = names.resolve(*self)?;
        // Parse rather than `Ident::new` so path keywords (`super`, `crate`) and
        // any lexically valid segment realize as their own tokens without panic.
        name.as_str()
            .parse::<TokenStream>()
            .map_err(|error| Error::Project(error.to_string()))
    }
}

impl ProjectRust for PathNode {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let segments = self
            .segments
            .iter()
            .map(|segment| segment.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The sole home of the dotted → `::` translation.
        Ok(quote! { #(#segments)::* })
    }
}

impl ProjectRust for TypeReference {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            TypeReference::Path(path) => path.project(names),
            TypeReference::Application(application) => application.project(names),
            TypeReference::Reference(reference) => reference.project(names),
            TypeReference::ImplTrait(impl_trait) => impl_trait.project(names),
            TypeReference::Slice(slice) => slice.project(names),
            TypeReference::Tuple(tuple) => tuple.project(names),
            TypeReference::Lifetime(lifetime) => lifetime.project_lifetime(names),
        }
    }
}

impl ProjectRust for ReferenceType {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let referent = self.referent.project(names)?;
        let mutable = match self.mutability {
            ReferenceMutability::Shared => TokenStream::new(),
            ReferenceMutability::Mutable => quote! { mut },
        };
        match self.lifetime {
            None => Ok(quote! { & #mutable #referent }),
            Some(lifetime) => {
                let lifetime = lifetime.project_lifetime(names)?;
                Ok(quote! { & #lifetime #mutable #referent })
            }
        }
    }
}

impl ProjectRust for SliceType {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let element = self.element.project(names)?;
        // The `[…]` slice delimiter — a delimiter re-sugaring the owning node chooses.
        Ok(quote! { [#element] })
    }
}

impl ProjectRust for TupleType {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let elements = self
            .elements
            .iter()
            .map(|element| element.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `(…)` tuple delimiter — a delimiter re-sugaring the owning node chooses.
        Ok(quote! { (#(#elements),*) })
    }
}

impl ProjectRust for ImplTraitType {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let bounds = self
            .bounds
            .iter()
            .map(|bound| bound.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { impl #(#bounds)+* })
    }
}

/// Realizing a stored identifier as a lifetime token `'name` — a second verb on the
/// identifier noun, distinct from its value projection, for the lifetime leaves a
/// reference type and lifetime parameter share.
trait ProjectLifetime {
    fn project_lifetime<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error>;
}

impl ProjectLifetime for Identifier {
    fn project_lifetime<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = names.resolve(*self)?;
        format!("'{}", name.as_str())
            .parse::<TokenStream>()
            .map_err(|error| Error::Project(error.to_string()))
    }
}

impl ProjectRust for TypeApplication {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let head = self.head.project(names)?;
        let arguments = self
            .arguments
            .iter()
            .map(|argument| argument.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `<…>` re-sugaring — one of the five allowed syntheses.
        Ok(quote! { #head<#(#arguments),*> })
    }
}

impl ProjectRust for Visibility {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        Ok(match self {
            Visibility::Public => quote! { pub },
            Visibility::Crate => quote! { pub(crate) },
            Visibility::Module(path) => {
                let path = path.project(names)?;
                quote! { pub(in #path) }
            }
            // The empty token stream: the "no `pub`" special case dissolves here.
            Visibility::Private => TokenStream::new(),
        })
    }
}

impl ProjectAttributeMeta for Attribute {
    fn project_meta<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            Attribute::Derive(group) => group.project(names),
            Attribute::ToolPath(path) => path.project(names),
            Attribute::HelperDerive(helper) => helper.project(names),
            Attribute::Configuration(configuration) => configuration.project(names),
            Attribute::Cfg(predicate) => {
                let predicate = predicate.project(names)?;
                Ok(quote! { cfg(#predicate) })
            }
        }
    }
}

impl ProjectRust for Attribute {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let meta = self.project_meta(names)?;
        Ok(quote! { #[#meta] })
    }
}

impl ProjectRust for DeriveGroup {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let paths = self
            .paths
            .iter()
            .map(|path| path.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // A trailing comma: prettyplease preserves it in the wrapped (multi-line)
        // derive the width-heavy goldens produce, and strips it when the derive
        // stays on one line — so one emission is byte-exact in both layouts.
        Ok(quote! { derive(#(#paths,)*) })
    }
}

impl ProjectRust for HelperDerive {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let path = self.path.project(names)?;
        let derived = self.derived.project(names)?;
        Ok(quote! { #path(#derived) })
    }
}

impl ProjectRust for ConfigurationAttribute {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let predicate = self.predicate.project(names)?;
        let inner = self.inner.project_meta(names)?;
        Ok(quote! { cfg_attr(#predicate, #inner) })
    }
}

impl ProjectRust for ConfigurationPredicate {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            ConfigurationPredicate::Feature(identifier) => {
                let name = names.resolve(*identifier)?;
                let literal = syn::LitStr::new(name.as_str(), proc_macro2::Span::call_site());
                Ok(quote! { feature = #literal })
            }
        }
    }
}

impl ProjectRust for Generics {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        if self.parameters.is_empty() {
            return Ok(TokenStream::new());
        }
        let parameters = self
            .parameters
            .iter()
            .map(|parameter| parameter.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { <#(#parameters),*> })
    }
}

impl ProjectRust for GenericParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            GenericParameter::Type(parameter) => parameter.project(names),
            GenericParameter::Lifetime(parameter) => parameter.project(names),
        }
    }
}

impl ProjectRust for TypeParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        if self.bounds.is_empty() {
            return Ok(name);
        }
        let bounds = self
            .bounds
            .iter()
            .map(|bound| bound.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #name: #(#bounds)+* })
    }
}

impl ProjectRust for LifetimeParameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        self.name.project_lifetime(names)
    }
}

impl ProjectRust for Field {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let type_reference = self.type_reference.project(names)?;
        Ok(quote! { #visibility #name: #type_reference })
    }
}

impl ProjectRust for Variant {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        match &self.payload {
            VariantPayload::Unit => Ok(name),
            VariantPayload::Tuple(types) => {
                let types = types
                    .iter()
                    .map(|type_reference| type_reference.project(names))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(quote! { #name(#(#types),*) })
            }
            VariantPayload::Struct(fields) => {
                let fields = fields
                    .iter()
                    .map(|field| field.project(names))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(quote! { #name { #(#fields),* } })
            }
        }
    }
}

impl ProjectRust for Newtype {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let wrapped_visibility = self.wrapped_visibility.project(names)?;
        let wrapped = self.wrapped.project(names)?;
        // `wrapped_visibility` is the tuple field's own visibility; `Private`
        // projects to the empty token stream, so a bare newtype emits
        // `struct Name(Wrapped);` and a `pub`-field newtype emits
        // `struct Name(pub Wrapped);` — the same node, no special case.
        Ok(quote! { #attributes #visibility struct #name(#wrapped_visibility #wrapped); })
    }
}

impl ProjectRust for Struct {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let fields = self
            .fields
            .iter()
            .map(|field| field.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #attributes #visibility struct #name #generics { #(#fields),* } })
    }
}

impl ProjectRust for Enumeration {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let variants = self
            .variants
            .iter()
            .map(|variant| variant.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #attributes #visibility enum #name #generics { #(#variants),* } })
    }
}

impl ProjectRust for Alias {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let target = self.target.project(names)?;
        Ok(quote! { #attributes #visibility type #name #generics = #target; })
    }
}

impl ProjectRust for Expression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        // Exhaustive over the closed Tier-1 algebra — no wildcard arm.
        match self {
            Expression::Receiver => Ok(quote! { self }),
            Expression::Path(path) => path.project(names),
            Expression::StringLiteral(text) => {
                let literal = syn::LitStr::new(text, proc_macro2::Span::call_site());
                Ok(quote! { #literal })
            }
            Expression::Reference(reference) => reference.project(names),
            Expression::Field(field) => field.project(names),
            Expression::Call(call) => call.project(names),
            Expression::MethodCall(method_call) => method_call.project(names),
            Expression::Match(match_expression) => match_expression.project(names),
            Expression::IntegerLiteral(literal) => literal.project(names),
            Expression::Array(array) => array.project(names),
            Expression::Try(try_expression) => try_expression.project(names),
            Expression::Closure(closure) => closure.project(names),
            Expression::Tuple(tuple) => tuple.project(names),
            Expression::Index(index) => index.project(names),
            Expression::Range(range) => range.project(names),
        }
    }
}

impl ProjectRust for TryExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let inner = self.inner.project(names)?;
        Ok(quote! { #inner? })
    }
}

impl ProjectRust for ClosureExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let parameters = self
            .parameters
            .iter()
            .map(|parameter| parameter.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        let body = self.body.project(names)?;
        Ok(quote! { |#(#parameters),*| #body })
    }
}

impl ProjectRust for TupleExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let elements = self
            .elements
            .iter()
            .map(|element| element.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `(…)` delimiter — a delimiter re-sugaring the owning node chooses. A
        // zero-element vector projects to the unit value `()`.
        Ok(quote! { (#(#elements),*) })
    }
}

impl ProjectRust for IndexExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let base = self.base.project(names)?;
        let index = self.index.project(names)?;
        // The `[…]` index delimiter — a delimiter re-sugaring the owning node chooses.
        Ok(quote! { #base[#index] })
    }
}

impl ProjectRust for RangeExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let start = match &self.start {
            None => TokenStream::new(),
            Some(start) => start.project(names)?,
        };
        let end = match &self.end {
            None => TokenStream::new(),
            Some(end) => end.project(names)?,
        };
        // The exclusive `..` operator — the range re-sugaring the owning node chooses.
        Ok(quote! { #start..#end })
    }
}

impl ProjectRust for IntegerLiteral {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        _names: &Resolver,
    ) -> Result<TokenStream, Error> {
        // Reconstruct the exact surface text from the value and its closed
        // representation — no raw token text was stored. Decimal is plain; hexadecimal
        // is lowercase `0x`, zero-padded to the recorded width.
        let text = match self.representation {
            IntegerRepresentation::Decimal => self.value.to_string(),
            IntegerRepresentation::Hexadecimal { minimum_digits } => {
                format!("0x{:0width$x}", self.value, width = minimum_digits as usize)
            }
        };
        text.parse::<TokenStream>()
            .map_err(|error| Error::Project(error.to_string()))
    }
}

impl ProjectRust for ArrayExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let elements = self
            .elements
            .iter()
            .map(|element| element.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `[…]` array delimiter — a delimiter re-sugaring the owning node chooses.
        Ok(quote! { [#(#elements),*] })
    }
}

impl ProjectRust for ReferenceExpression {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let referent = self.referent.project(names)?;
        Ok(quote! { & #referent })
    }
}

impl ProjectRust for TupleFieldAccess {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let base = self.base.project(names)?;
        // A tuple index token (`0`) with no integer suffix — the `.0` re-sugaring.
        let index = syn::Index::from(self.index as usize);
        Ok(quote! { #base.#index })
    }
}

impl ProjectRust for Call {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let callee = self.callee.project(names)?;
        let turbofish = if self.type_arguments.is_empty() {
            TokenStream::new()
        } else {
            let type_arguments = self
                .type_arguments
                .iter()
                .map(|type_argument| type_argument.project(names))
                .collect::<Result<Vec<_>, _>>()?;
            quote! { ::<#(#type_arguments),*> }
        };
        let arguments = self
            .arguments
            .iter()
            .map(|argument| argument.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #callee #turbofish (#(#arguments),*) })
    }
}

impl ProjectRust for Callee {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            Callee::Path(path) => path.project(names),
            Callee::Qualified(qualified) => qualified.project(names),
        }
    }
}

impl ProjectRust for QualifiedPath {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let self_type = self.self_type.project(names)?;
        let trait_path = self.trait_path.project(names)?;
        let member = self
            .member
            .iter()
            .map(|segment| segment.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { < #self_type as #trait_path >::#(#member)::* })
    }
}

impl ProjectRust for MethodCall {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let receiver = self.receiver.project(names)?;
        let method = self.method.project(names)?;
        let turbofish = if self.type_arguments.is_empty() {
            TokenStream::new()
        } else {
            let type_arguments = self
                .type_arguments
                .iter()
                .map(|type_argument| type_argument.project(names))
                .collect::<Result<Vec<_>, _>>()?;
            quote! { ::<#(#type_arguments),*> }
        };
        let arguments = self
            .arguments
            .iter()
            .map(|argument| argument.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #receiver.#method #turbofish (#(#arguments),*) })
    }
}

impl ProjectRust for Match {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let scrutinee = self.scrutinee.project(names)?;
        let arms = self
            .arms
            .iter()
            .map(|arm| arm.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { match #scrutinee { #(#arms)* } })
    }
}

impl ProjectRust for MatchArm {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let pattern = self.pattern.project(names)?;
        let body = self.body.project(names)?;
        Ok(quote! { #pattern => #body, })
    }
}

impl ProjectRust for Pattern {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            Pattern::Path(path) => path.project(names),
            Pattern::TupleVariant(tuple_variant) => tuple_variant.project(names),
            Pattern::Wildcard => Ok(quote! { _ }),
        }
    }
}

impl ProjectRust for TupleVariantPattern {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let path = self.path.project(names)?;
        let elements = self
            .elements
            .iter()
            .map(|element| element.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(quote! { #path(#(#elements),*) })
    }
}

impl ProjectRust for PatternElement {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            PatternElement::Wildcard => Ok(quote! { _ }),
            PatternElement::Binding(identifier) => identifier.project(names),
        }
    }
}

impl ProjectRust for Receiver {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        _names: &Resolver,
    ) -> Result<TokenStream, Error> {
        Ok(match self {
            Receiver::Value => quote! { self },
            Receiver::Reference => quote! { &self },
        })
    }
}

impl ProjectRust for Parameter {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        let type_reference = self.type_reference.project(names)?;
        Ok(quote! { #name: #type_reference })
    }
}

impl ProjectRust for Block {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let statements = self
            .statements
            .iter()
            .map(|statement| statement.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        let tail_expression = self.tail_expression.project(names)?;
        // The `{ … }` block delimiter — one of the five allowed syntheses. The
        // statements carry their own `;`; the tail expression carries none.
        Ok(quote! { { #(#statements)* #tail_expression } })
    }
}

impl ProjectRust for Statement {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            Statement::Let(let_statement) => let_statement.project(names),
            Statement::Expression(expression) => {
                let expression = expression.project(names)?;
                Ok(quote! { #expression; })
            }
        }
    }
}

impl ProjectRust for LetStatement {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let mutable = match self.binding {
            LetBinding::Immutable => TokenStream::new(),
            LetBinding::Mutable => quote! { mut },
        };
        let name = self.name.project(names)?;
        let value = self.value.project(names)?;
        Ok(quote! { let #mutable #name = #value; })
    }
}

impl ProjectRust for Function {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let generics = self.generics.project(names)?;
        let mut inputs = Vec::new();
        if let Some(receiver) = &self.receiver {
            inputs.push(receiver.project(names)?);
        }
        for parameter in &self.parameters {
            inputs.push(parameter.project(names)?);
        }
        let return_type = match &self.return_type {
            None => TokenStream::new(),
            Some(type_reference) => {
                let type_reference = type_reference.project(names)?;
                quote! { -> #type_reference }
            }
        };
        let body = self.body.project(names)?;
        Ok(quote! { #attributes #visibility fn #name #generics (#(#inputs),*) #return_type #body })
    }
}

impl ProjectRust for ImplBlock {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let generics = self.generics.project(names)?;
        let self_type = self.self_type.project(names)?;
        let items = self
            .items
            .iter()
            .map(|item| item.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        let head = match &self.implemented_trait {
            None => quote! { impl #generics #self_type },
            Some(implemented_trait) => {
                let implemented_trait = implemented_trait.project(names)?;
                quote! { impl #generics #implemented_trait for #self_type }
            }
        };
        Ok(quote! { #attributes #head { #(#items)* } })
    }
}

impl ProjectRust for ImplItem {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        match self {
            ImplItem::Method(function) => function.project(names),
            ImplItem::AssociatedType(associated_type) => associated_type.project(names),
            ImplItem::AssociatedConst(associated_const) => associated_const.project(names),
        }
    }
}

impl ProjectRust for AssociatedType {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let name = self.name.project(names)?;
        let value = self.value.project(names)?;
        Ok(quote! { type #name = #value; })
    }
}

impl ProjectRust for Const {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let type_reference = self.type_reference.project(names)?;
        let value = self.value.project(names)?;
        Ok(quote! { #attributes #visibility const #name: #type_reference = #value; })
    }
}

impl ProjectRust for Module {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let name = self.name.project(names)?;
        let items = self
            .items
            .iter()
            .map(|item| item.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `{…}` inline-module delimiter — a delimiter re-sugaring the owning node
        // chooses.
        Ok(quote! { #attributes #visibility mod #name { #(#items)* } })
    }
}

impl ProjectRust for Use {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        let attributes = self.attributes.project_preamble(names)?;
        let visibility = self.visibility.project(names)?;
        let base = self.base.project(names)?;
        let group = self
            .group
            .iter()
            .map(|identifier| identifier.project(names))
            .collect::<Result<Vec<_>, _>>()?;
        // The `::` between base and group, and the `{…}` brace group, are the
        // delimiter re-sugaring the owning node chooses.
        Ok(quote! { #attributes #visibility use #base::{ #(#group),* }; })
    }
}

impl ProjectRust for CoreItem {
    fn project<Resolver: NameResolver + ?Sized>(
        &self,
        names: &Resolver,
    ) -> Result<TokenStream, Error> {
        // Exhaustive over the closed algebra — no wildcard arm, so a new item kind
        // is a compile error until its projection is written.
        match self {
            CoreItem::Newtype(newtype) => newtype.project(names),
            CoreItem::Struct(structure) => structure.project(names),
            CoreItem::Enumeration(enumeration) => enumeration.project(names),
            CoreItem::Alias(alias) => alias.project(names),
            CoreItem::ImplBlock(impl_block) => impl_block.project(names),
            CoreItem::Function(function) => function.project(names),
            CoreItem::Use(use_import) => use_import.project(names),
            CoreItem::Const(const_item) => const_item.project(names),
            CoreItem::Module(module) => module.project(names),
        }
    }
}

/// A rendered Rust textual form — the output noun of the writer and the input noun
/// of the reader. It carries the projected Rust source text; formatting is
/// prettyplease's, owned by the constructors here.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustSource(String);

impl RustSource {
    /// Wrap already-rendered Rust text (e.g. a golden file read from disk).
    pub fn new(text: impl Into<String>) -> Self {
        Self(text.into())
    }

    /// The rendered text.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consume into the owned text.
    pub fn into_string(self) -> String {
        self.0
    }

    /// Project one CoreLogos item to byte-exact Rust: assemble its token structure
    /// through [`ProjectRust`], then run the single `prettyplease` pass that owns
    /// all formatting. The attribute preamble (including `#[rustfmt::skip]`) is
    /// stored data on the item, so it is part of the projected tokens, not
    /// prepended here.
    pub fn project_item<Resolver: NameResolver + ?Sized>(
        item: &CoreItem,
        names: &Resolver,
    ) -> Result<Self, Error> {
        let tokens = item.project(names)?;
        let file: syn::File =
            syn::parse2(tokens).map_err(|error| Error::Project(error.to_string()))?;
        Ok(Self(prettyplease::unparse(&file)))
    }

    /// Project several CoreLogos items in a *single* `prettyplease` pass — the
    /// blank-line layout between them is prettyplease's own (consecutive scalar type
    /// aliases pack with no blank; a `use` after them takes no blank either). This is
    /// the block-level render the fixed module prelude needs: the four scalar aliases
    /// as one blank-free block. For a one-item slice it equals [`Self::project_item`].
    pub fn project_items<Resolver: NameResolver + ?Sized>(
        items: &[CoreItem],
        names: &Resolver,
    ) -> Result<Self, Error> {
        let mut tokens = TokenStream::new();
        for item in items {
            tokens.extend(item.project(names)?);
        }
        let file: syn::File =
            syn::parse2(tokens).map_err(|error| Error::Project(error.to_string()))?;
        Ok(Self(prettyplease::unparse(&file)))
    }

    /// Project a whole module: the `// @generated by logos` header (build-stamped
    /// with this crate's own version), then each item's single-pass render,
    /// separated by a blank line — the generated-module shape. Per-item
    /// byte-exactness is the acceptance unit; this is the convenience
    /// whole-module view.
    pub fn project_module<Resolver: NameResolver + ?Sized>(
        items: &[CoreItem],
        names: &Resolver,
    ) -> Result<Self, Error> {
        let mut text = String::new();
        text.push_str(GENERATED_HEADER);
        text.push_str("\n\n");
        for item in items {
            text.push_str(Self::project_item(item, names)?.as_str());
            text.push('\n');
        }
        Ok(Self(text))
    }
}
